species:
  # Aar:
  #   fai: step0/Aar.fa.fai
  #   cool: cools/Aar.mcool
  Asu:
    fai: step0/Asu.fa.fai
    cool: cools/Asu.mcool
  Ath:
    fai: step0/Ath.fa.fai
    cool: cools/Ath.mcool

pairs:
  - { a: Aar, b: Asu, link: step0/Aar_Asu.link }
  # - { a: Aar, b: Ath, link: step0/Aar_Ath.link }
  # - { a: Asu, b: Ath, link: step0/Asu_Ath.link }

cool_group: /resolutions/40000

parameters:
  link2mark_parameters: "--thr-len 300 --step-len 150"
  prepare_parameters: "--max-distance 500000000 --inter"
  liftcontacts_parameters: "--agg-frame 400000 --dups-filter coverage --model balanced"
  contact_stat_parameters: "--bins 400 --max-dist-mb 5 --cmap pinkblue"     
  metric_parameters: "--frames 8 --metric pbad --random-stats"
